### ISSUE TITLE
build error: must specify a user that is numeric and within the range of allowed users

### ISSUE THREAD

**Issue by christian-posta** [dhirajsb/fuse-sti#2]
The s2i builder needs to use a numeric user:

Build error: image "dhirajsb/fuse-sti@sha256:eeb1779cefa11f1cc6baffde1fb0fa6cab3f10746af36bbac0e3815c73fabc84" must specify a user that is numeric and within the range of allowed users

Similar to this:
https://bugzilla.redhat.com/show_bug.cgi?id=1261423

**Comment by dhirajsb** [comment]
Fixed with https://github.com/dhirajsb/fuse-sti/commit/bc12e4a17a39170811cd0299a9aa739b2eda32c1
